version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    container_name: flight-container
