name: Tests for Next.js app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  NextJS-Tests:
    name: Tests for Next.js app
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version:  '22'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest tests
        run: npm test