name: Run Tests

on:
  pull_request:
<<<<<<< HEAD
=======
    branches:
      - main
>>>>>>> b31a6e85fc7d107a154159f4c85deada3d9cb0c4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v2

      - name: Setup Node.js
=======
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
>>>>>>> b31a6e85fc7d107a154159f4c85deada3d9cb0c4
        uses: actions/setup-node@v3
        with:
          node-version: '22'

<<<<<<< HEAD
      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
=======
      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
>>>>>>> b31a6e85fc7d107a154159f4c85deada3d9cb0c4
