name: Tests for Next.js app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  NextJS-Tests:
    name: Tests for Next.js app
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: List node_modules
        run: ls -la node_modules

      - name: List node_modules/.bin
        run: ls -la node_modules/.bin
